title: robot_odyssey-godot;;workdir: ~/dev/robot_odyssey-godot;; command:;; profile:
title: godoctopus2;;workdir: ~/dev/robot_odyssey-godot/modules/godoctopus2;; command:;; profile:
title: octopus2;;workdir: ~/dev/robot_odyssey-godot/modules/godoctopus2/src/octopus2;; command:;; profile:
title: 3d-experiments;;workdir: ~/godot_workspace/3d-experiments/;; command: ;; profile: